config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :contents
  resources :variants
  resources :sections do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  resources :documents

  root 'main#index'
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :document
  belongs_to :section
  belongs_to :variant

  validates :body, presence: true
  validates :document, presence: true
  validates :section, presence: true
  validates :variant, presence: true
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
    @body_html = markdown.render(@content.body)
  end

  # GET /contents/new
  def new
    @document = Document.find(params['document'])
    @section = Section.find(params['section'])
    @variant = Variant.find(params['variant'])
    @content = Content.new(document: @document, section: @section, variant: @variant)
  end

  # GET /contents/1/edit
  def edit
    @document = @content.document
    @section = @content.section
    @variant = @content.variant
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to document_path(@content.document, variant: @content.variant), notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        @document = @content.document
        @section = @content.section
        @variant = @content.variant

        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to document_path(@content.document, variant: @content.variant), notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        @document = @content.document
        @section = @content.section
        @variant = @content.variant

        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:document_id, :section_id, :variant_id, :body)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :document_id %>
  <%= form.hidden_field :section_id %>
  <%= form.hidden_field :variant_id %>
  <h2><%= @document.title %> : <%= @section.title %> : <%= @variant.name %></h2>

  <div class="form-group">
    <%= form.text_area :body, id: :content_body, rows:20, cols: 80, spellcheck: false %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

<script>
    new SimpleMDE({
        element: document.getElementById("content_body"),
        autofocus: true
    });
</script>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table class="table">
  <thead>
    <tr>
      <th>Document</th>
      <th>Section</th>
      <th>Variant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.document.title %></td>
        <td><%= content.section.title %></td>
        <td><%= content.variant.name %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @content.document.title %>
</p>

<p>
  <strong>Section:</strong>
  <%= @content.section.title %>
</p>

<p>
  <strong>Variant:</strong>
  <%= @content.variant.name %>
</p>

<p><%= raw @body_html %></p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>