config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :contents
  resources :variants
  resources :sections do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  resources :documents

  root 'main#index'
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :document

  has_many :contents, dependent: :destroy

  validates :title, presence: true
  validates :document, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy, :move_up, :move_down]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @document = Document.find(params['document'])
    @section = Section.new(document: @document)
  end

  # GET /sections/1/edit
  def edit
    @document = @section.document
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)
    @section.number = @section.document.sections.size + 1

    respond_to do |format|
      if @section.save
        format.html { redirect_to document_path(@section.document), notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        @document = @section.document

        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to document_path(@section.document), notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        @document = @section.document

        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to document_path(@section.document), notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move_up
    if @section.number != 0
      previous_section = @section.document.sections[@section.number - 1]

      previous_section.number = @section.number
      previous_section.save

      @section.number = @section.number - 1
      @section.save

      redirect_to(@section.document)
    end
  end

  def move_down
    if @section.number != @section.document.sections.length - 1
      next_section = @section.document.sections[@section.number + 1]

      next_section.number = @section.number
      next_section.save

      @section.number = @section.number + 1
      @section.save

      redirect_to(@section.document)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :document_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :document_id %>
    <h2><%= @document.title %></h2>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :section_title, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Document</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= link_to section.title, section %></td>
        <td><%= link_to section.document.title, section.document %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Section', new_section_path, class: 'btn btn-primary' %></p>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Document:</strong>
  <%= @section.document %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>