config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :contents
  resources :variants
  resources :sections do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  resources :documents

  root 'main#index'
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :sections, -> { order(:number) }, dependent: :destroy
  has_many :variants, dependent: :destroy
  has_many :contents, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all.order(:title)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @contents = @document.contents
    @variants = @document.variants.order(:name)

    if !@variants.empty?
      @variant = Variant.find(params[:variant] || @variants.first.try(:id)) || nil
    end

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    section = Section.new(title: 'Introduction')
    variant = Variant.new(name: 'Main')
    content = Content.new(body: 'Your content here', section: section, variant: variant)
    @document.sections << section
    @document.variants << variant
    @document.contents << content

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :description)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :document_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :document_description, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<% @documents.each do |document| %>
    <h2><%= link_to document.title, document %></h2>

    <p class="lead"><%= document.description %></p>
<% end %>

<p><%= link_to 'New Document', new_document_path, class: 'btn btn-primary' %></p>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @document.title %> - <%= @variant.try(:name) %></h1>

<p class="lead"><%= @document.description %></p>

<% if !@document.variants.empty? %>
  <ul class="nav nav-tabs">
  <% @variants.each do |variant| %>
    <li role="presentation" class="<%= 'active' if variant == @variant %>">
      <%= link_to variant.name, document_path(variant: variant) %>
    </li>
  <% end %>
  </ul>
<% end %>

<% @document.sections.order(:number).each do |section| %>
    <div class="row">
      <div class="col-md-10">
        <h2><%= section.title %></h2>
      </div>
      <div class="col-md-2">
        <h2>
          <div class="btn-group" role="group">
            <%= link_to edit_section_path(section), class: 'btn btn-default btn-xs' do %>
                <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
            <% end %>
            <% if section.number != 0 %>
              <%= link_to move_up_section_path(section), class: 'btn btn-default btn-xs', :method => :put do %>
                    <i class="glyphicon glyphicon-arrow-up" aria-hidden="true"></i>
              <% end %>
            <% else %>
                <span class="btn btn-default btn-xs disabled"><i class="glyphicon glyphicon-arrow-up" aria-hidden="true"></i></span>
            <% end %>
            <% if section.number != @document.sections.length - 1 %>
              <%= link_to move_down_section_path(section), class: 'btn btn-default btn-xs', :method => :put do %>
                    <i class="glyphicon glyphicon-arrow-down" aria-hidden="true"></i>
              <% end %>
            <% else %>
                <span class="btn btn-default btn-xs disabled"><i class="glyphicon glyphicon-arrow-down" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to section, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
                <i class="glyphicon glyphicon-remove" aria-hidden="true"></i>
            <% end %>
          </div>
        </h2>
      </div>
    </div>

    <% content = @document.contents.where(section: section, variant: @variant).first %>

    <div class="row">
      <div class="col-md-10">
        <% if content %>
          <%= raw @markdown.render(content.try(:body)) %>
        <% else %>
            <div class="alert alert-warning" role="alert">No content for this section yet.</div>
        <% end %>
      </div>
      <div class="col-md-2">
        <% if content %>
          <%= link_to edit_content_path(content), class: 'btn btn-default btn-xs' do %>
                <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
          <% end %>
        <% else %>
            <% if !@variant.nil? %>
                <%= link_to new_content_path(document: @document, section: section, variant: @variant), class: 'btn btn-default btn-xs' do %>
                    <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
                <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

<hr>

<div class="row">
  <div class="col-md-8">
    <%= link_to 'Edit Document', edit_document_path(@document), class: 'btn btn-default btn-small' %>
    <% if @variant %>
      <%= link_to 'Edit Variant', edit_variant_path(@variant), class: 'btn btn-default btn-small' %>
    <% end %>
    <%= link_to 'Add Section', new_section_path(document: @document), class: 'btn btn-default btn-small' %>
    <%= link_to 'Add Variant', new_variant_path(document: @document), class: 'btn btn-default btn-small' %>
  </div>
  <div class="col-md-4 pull-right">
    <% if @variant %>
      <%= link_to 'Delete Variant', @variant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
    <% end %>
    <%= link_to 'Delete Document', @document, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
  </div>
</div>