config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :contents
  resources :variants
  resources :sections do
    member do
      put 'move_up'
      put 'move_down'
    end
  end
  resources :documents

  root 'main#index'
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :document

  has_many :contents, dependent: :destroy

  validates :name, presence: true
  validates :document, presence: true
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @document = Document.find(params['document'])
    @variant = Variant.new(document: @document)
  end

  # GET /variants/1/edit
  def edit
    @document = @variant.document
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to document_path(@variant.document, variant: @variant), notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        @document = @variant.document

        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to document_path(@variant.document, variant: @variant), notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        @document = @variant.document

        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    document = @variant.document

    @variant.destroy
    respond_to do |format|
      format.html { redirect_to document_path(document), notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:name, :document_id)
    end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_with(model: variant, local: true) do |form| %>
  <% if variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :document_id %>
    <h2><%= @document.title %></h2>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :variant_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/variants/edit.html.erb
<h1>Editing Variant</h1>

<%= render 'form', variant: @variant %>

app/views/variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Document</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= link_to variant.name, variant %></td>
        <td><%= link_to variant.document.title, variant.document %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Variant', new_variant_path, class: 'btn btn-primary' %></p>

app/views/variants/new.html.erb
<h1>New Variant</h1>

<%= render 'form', variant: @variant %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @variant.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @variant.document %>
</p>

<%= link_to 'Edit', edit_variant_path(@variant) %> |
<%= link_to 'Back', variants_path %>